### ISSUE TITLE
ICGC25k azure transfer - LINC-JP failed jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#194] opened 2021-08-30 16:29 UTC
Error messages for failed jobs
[LINC-JP_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092099/LINC-JP_job_state.txt)

**Comment by hknahal** [comment] 2021-09-02 21:12
Summary of failed jobs:

**2 jobs failed due to objectID mismatch:**

- Azure SONG assigns the object ID to a different file than Collab SONG:
  Example 1:
   - Collab SONG: https://song.cancercollaboratory.org/studies/LINC-JP/files/12216a73-6c5c-5d5d-b6d8-7e5f05066056
   - Azure SONG: https://song.azure.icgc.overture.bio/studies/LINC-JP/files/12216a73-6c5c-5d5d-b6d8-7e5f05066056

The Object ID "12216a73-6c5c-5d5d-b6d8-7e5f05066056" is assigned to a different file in Azure SONG:
```
Object ID: 12216a73-6c5c-5d5d-b6d8-7e5f05066056
Collab SONG file name: bundle.EGAR00001198664.xml
Azure SONG file name: e2962083470ad373bd9f1ad67ba6d936.HCC20T_CAGATC_L002_R2_017.fastq.bz2
```
 
   Example 2:
   - Collab SONG: https://song.cancercollaboratory.org/studies/LINC-JP/analysis/EGAR00001119060
   - Azure SONG: https://song.azure.icgc.overture.bio/studies/LINC-JP/analysis/EGAR00001119060

The file "d0699ff9a975da4164ec2c3613f70a7.HCC122T_ACAGTG_L002_R1_040.fastq.bz2" is assigned a different objectID than Collab SONG:
```
File name: d0699ff9a975da4164ec2c3613f70a7.HCC122T_ACAGTG_L002_R1_040.fastq.bz2
Collab SONG object ID: ee3f8424-7faf-57a2-9cf7-94ed5fd9372b
Azure SONG object ID:  f6d3bc8d-8b3d-59ab-bb2c-154c6c9c020c
```

**2 jobs failed with no error:**

EGAR00001111042
EGAR00001107013

**Comment by akachru-github** [comment] 2021-09-14 20:11
- Root cause was discovered: https://github.com/icgc-argo/workflow-roadmap/issues/196
- Data was re-transferred

**Closed as completed by akachru-github** 2021-09-14 20:11 UTC
