### ISSUE TITLE
Prepare for May data release - QC OCCAMS-GB

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#118] opened 2021-04-08 18:41 UTC
Wait till OCCAMS-GR finish variant calling before QC the entire project. ETA early May. For every donor we have alignment, we need to ensure we have successful Sanger and Mutect calls. Will involve coordination with Rosi.

**Comment by lindaxiang** [comment] 2021-04-08 20:31
There are some duplicated runs reported and need investigation.
Next step is to suppress all the duplicate analysis.

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**input\_analysisType**|**latest\_complete\_time**|**runId**|**complete\_time**|**output\_analysis\_to\_suppress**|**reason**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
OCCAMS-GB|DO234352|SA595129|Normal|WGS|b3706265-f829-4c11-b062-65f8298c1150|sequencing\_experiment|2021-04-05 21:12|wes-ed1a38ba733c49569b078bb010a73a2e|2021-04-05 20:18|['343ff395-61ef-4937-bff3-9561efa937da', '58170ef3-b3e0-43f1-970e-f3b3e063f1a4']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234150|SA596941|Tumour|WGS|21b18de8-aedd-4650-b18d-e8aedd765064|sequencing\_experiment|2021-04-17 3:35|wes-80c4a3022d594565af6c03819c98dbe1|2021-04-14 10:04|['af58f8e6-4dff-4fe0-98f8-e64dff5fe02f']|failed\_run\_output\_analysis
OCCAMS-GB|DO234259|SA547436|Tumour|WGS|6dfb9890-3050-4dbf-bb98-903050edbf51|sequencing\_experiment|2021-04-13 15:59|wes-ebca3b327584462c9d8affaf747e1773|2021-04-13 10:52|['2b0a8f54-7180-46a4-8a8f-547180f6a48d', 'a4f99868-e63c-4662-b998-68e63cf662b6']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234243|SA594385|Tumour|WGS|3c415e48-eb05-4dc8-815e-48eb05edc8ab|sequencing\_experiment|2021-04-17 9:09|wes-1c2227be968b4683972955de23669b39|2021-04-14 10:04|['5a2fc1d1-6acd-4cb4-afc1-d16acd7cb4b4']|failed\_run\_output\_analysis
OCCAMS-GB|DO234262|SA597274|Tumour|WGS|522f8991-c7d2-4ec8-af89-91c7d27ec860|sequencing\_experiment|2021-04-13 7:05|wes-72457709cce94d38add8cf1801365c6f|2021-04-13 5:03|['4bffbd2f-5582-4e33-bfbd-2f5582ee33be', '6e1b6f32-9fba-435d-9b6f-329fba735d11']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234346|SA595094|Normal|WGS|6838bd95-7747-433b-b8bd-957747c33b07|sequencing\_experiment|2021-04-05 23:01|wes-28cf3dca451c4ee9a0a05b7f4a4a0a6c|2021-04-05 19:12|['36d7f896-f46c-451e-97f8-96f46ca51e6e', 'a0fc0118-4558-4b65-bc01-184558fb65bd']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234346|SA595094|Normal|WGS|6838bd95-7747-433b-b8bd-957747c33b07|sequencing\_experiment|2021-04-05 23:01|wes-a28524a6aec24d1d9f16c48890f18e44|2021-04-05 20:04|['259fd268-bc11-40c5-9fd2-68bc11f0c5df', 'e3c3e5d2-46ab-4314-83e5-d246abf314bd']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234346|SA595094|Normal|WGS|6838bd95-7747-433b-b8bd-957747c33b07|sequencing\_experiment|2021-04-05 23:01|wes-691eaf0a44974eea8bd930d2fbf86ea4|2021-04-05 18:50|['4edc191d-336e-4269-9c19-1d336e426976', 'c096cffa-2b24-4cb5-96cf-fa2b247cb5ac']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234255|SA597346|Tumour|WGS|9950139c-bbe4-4c47-9013-9cbbe42c47ed|sequencing\_experiment|2021-04-13 9:58|wes-1f49c307eddb4f539113f539f136b025|2021-04-13 7:20|['d121666a-d824-4b97-a166-6ad824cb97de', '4eb815bf-fa69-4eb7-b815-bffa699eb79b']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234204|SA597188|Tumour|WGS|6f33dacc-a404-4a63-b3da-cca4048a6327|sequencing\_experiment|2021-04-06 0:40|wes-6655ca8d613e4cf1922ff24ad7238e17|2021-04-05 21:03|['517d574f-5710-4f82-bd57-4f57107f8252', '66767029-abb9-44c7-b670-29abb9a4c7a8']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234352|SA595137|Tumour|WGS|9110449e-ef5d-4feb-9044-9eef5dafebbc|sequencing\_experiment|2021-04-06 17:11|wes-73dd0796861f4c409910d920a134873d|2021-04-06 15:51|['70731493-daa9-447b-b314-93daa9d47b6a', 'c58dcfd4-6b52-49a2-8dcf-d46b5209a252']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234352|SA595137|Tumour|WGS|9110449e-ef5d-4feb-9044-9eef5dafebbc|sequencing\_experiment|2021-04-06 17:11|wes-f56bf58eccb64c2780290f5c383be74e|2021-04-06 17:06|['cd39cd14-067e-401f-b9cd-14067ee01f55', 'ba2b1b25-242f-44fb-ab1b-25242fd4fb93']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234272|SA597337|Tumour|WGS|4ed74435-ce41-4c15-9744-35ce411c153b|sequencing\_experiment|2021-04-17 6:44|wes-6f956d6615c0449786df8064c9562090|2021-04-14 10:01|['051f450c-4d30-48df-9f45-0c4d3048df75']|failed\_run\_output\_analysis
OCCAMS-GB|DO234272|SA597337|Tumour|WGS|4ed74435-ce41-4c15-9744-35ce411c153b|sequencing\_experiment|2021-04-17 6:44|wes-f067428c6c184499ac77498299a5dd55| | |duplicated\_running\_jobs
OCCAMS-GB|DO234272|SA597329|Normal|WGS|fbb9ce6c-7331-4661-b9ce-6c7331266182|sequencing\_experiment|2021-04-21 11:15|wes-d29c0664c3624313b7f3885297daa14a|2021-04-14 10:02|['75e6d569-27c1-47e8-a6d5-6927c1d7e89e']|failed\_run\_output\_analysis
OCCAMS-GB|DO234272|SA597329|Normal|WGS|fbb9ce6c-7331-4661-b9ce-6c7331266182|sequencing\_experiment|2021-04-21 11:15|wes-788ec8b348524ad4bcd56e0feb5d4533|2021-04-17 6:37|['672bbe58-96a9-4b2d-abbe-5896a94b2de6', 'bdf27793-3dfd-486e-b277-933dfdf86ec2']|duplicated\_run\_output\_analysis

**Comment by lindaxiang** [comment] 2021-04-13 18:19
More duplicated analysis are showing up. Will add the full list of duplicated analysis after all aln complete. 
It may be due to the potential bug in Model Tee: https://github.com/icgc-argo/workflow-roadmap/issues/121

**Comment by lindaxiang** [comment] 2021-04-14 11:08
There are some aln jobs reported in the attached file which were NOT queued and ran. It may contain the failed jobs and the previous suppressed analysis due to renaming ID issue recorded in
https://github.com/icgc-argo/workflow-roadmap/issues/53. 
Will need some cross-check and confirmation.
[OCCAMS-GB.aln_jobs.txt](https://github.com/icgc-argo/workflow-roadmap/files/6310361/OCCAMS-GB.aln_jobs.txt)

**Comment by hknahal** [comment] 2021-04-14 17:00
@lindaxiang I confirmed all analysis IDs in [OCCAMS-GB.aln_jobs.txt](https://github.com/icgc-argo/workflow-roadmap/files/6310361/OCCAMS-GB.aln_jobs.txt) were suppressed due to re-naming ID issues in https://github.com/icgc-argo/workflow-roadmap/issues/53  except for these four donors. With the exception of DO234165, all donors were investigated and action plans for them are mentioned in https://github.com/icgc-argo/argo-meta/issues/32

1. **DO234206**: The tumour sample is missing in ARGO and the SONG payload has been generated, but since this is one of the donors affected by the re-naming issue, we decided to migrate the missing tumour sample later if the program submits clinical data for this donor (see [here|https://github.com/icgc-argo/argo-meta/issues/32#issuecomment-814239774] for more details on this donor). We can suppress this donor for now.

2. **DO234201**: The tumour sample is missing in ARGO and the SONG payload has been generated, but since this is one of the donors affected by the re-naming issue, we decided to migrate the missing tumour sample later if the program submits clinical data for this donor (see [here|https://github.com/icgc-argo/argo-meta/issues/32#issuecomment-814239774] for more details on this donor). We can suppress this donor for now.

3. **DO234196**: The normal sample was not transferred from ICGC to ARGO because the SONG payload in Collab was unpublished. The SONG payload has been set to "PUBLISHED" now, so when we re-index Collab (after the EGA transfer is complete (https://github.com/icgc-argo/ega-file-transfer/issues/12), the file will show in the repo and will be transferred over to ARGO. 

4. **DO234165**: This donor was affected by the re-naming issue but it was not one of the donors suppressed earlier. The SONG payloads are published for this donor: https://intermediate-song.rdpc-qa.cancercollaboratory.org/studies/OCCAMS-GB/analysis/search/id?donorId=DO234165 Unclear why this donor's jobs failed.


## Details:

|Donor ID|Sample ID|Analysis ID|
|-- | -- | -- |
|DO234165 | SA596918 | d77d4006-78fb-46a5-bd40-0678fb46a50d|
|DO234165 | SA596893 | 6f6b2303-0eb8-4412-ab23-030eb8a41234|
|DO234165 | SA596911 | fa81432b-c992-44a3-8143-2bc992b4a38e|
|DO234165 | SA596880 | c860fa5a-65a8-438d-a0fa-5a65a8838dd5|
|DO234196 | SA594630 | 026c0989-0e27-499b-ac09-890e27399b4c|
|DO234201 | SA597222 | 56c16c86-dacd-4531-816c-86dacd8531fa|
|DO234206 | SA597153 | f3f5cc9f-a963-4578-b5cc-9fa963e57847|

**Comment by lindaxiang** [comment] 2021-04-16 19:43
Thanks @hknahal .
For the aln jobs which were suppressed due to  re-naming ID issues in #53 , should we re-run them later?

**Comment by hknahal** [comment] 2021-04-16 19:45
@lindaxiang Yes, we can re-run the aln jobs that were suppressed due to re-naming issues

**Comment by lindaxiang** [comment] 2021-04-22 13:10
> There are some duplicated runs reported and need investigation.
> Next step is to suppress all the duplicate analysis.
> 
> **studyId**	**donorId**	**sampleId**	**tumourNormalDesignation**	**experimental_strategy**	**input_analysisId**	**input_analysisType**	**latest_complete_time**	**runId**	**complete_time**	**output_analysis_to_suppress**	**reason**
> OCCAMS-GB	DO234352	SA595129	Normal	WGS	b3706265-f829-4c11-b062-65f8298c1150	sequencing_experiment	2021-04-05 21:12	wes-ed1a38ba733c49569b078bb010a73a2e	2021-04-05 20:18	['343ff395-61ef-4937-bff3-9561efa937da', '58170ef3-b3e0-43f1-970e-f3b3e063f1a4']	duplicated_run_output_analysis
> OCCAMS-GB	DO234150	SA596941	Tumour	WGS	21b18de8-aedd-4650-b18d-e8aedd765064	sequencing_experiment	2021-04-17 3:35	wes-80c4a3022d594565af6c03819c98dbe1	2021-04-14 10:04	['af58f8e6-4dff-4fe0-98f8-e64dff5fe02f']	failed_run_output_analysis
> OCCAMS-GB	DO234259	SA547436	Tumour	WGS	6dfb9890-3050-4dbf-bb98-903050edbf51	sequencing_experiment	2021-04-13 15:59	wes-ebca3b327584462c9d8affaf747e1773	2021-04-13 10:52	['2b0a8f54-7180-46a4-8a8f-547180f6a48d', 'a4f99868-e63c-4662-b998-68e63cf662b6']	duplicated_run_output_analysis
> OCCAMS-GB	DO234243	SA594385	Tumour	WGS	3c415e48-eb05-4dc8-815e-48eb05edc8ab	sequencing_experiment	2021-04-17 9:09	wes-1c2227be968b4683972955de23669b39	2021-04-14 10:04	['5a2fc1d1-6acd-4cb4-afc1-d16acd7cb4b4']	failed_run_output_analysis
> OCCAMS-GB	DO234262	SA597274	Tumour	WGS	522f8991-c7d2-4ec8-af89-91c7d27ec860	sequencing_experiment	2021-04-13 7:05	wes-72457709cce94d38add8cf1801365c6f	2021-04-13 5:03	['4bffbd2f-5582-4e33-bfbd-2f5582ee33be', '6e1b6f32-9fba-435d-9b6f-329fba735d11']	duplicated_run_output_analysis
> OCCAMS-GB	DO234346	SA595094	Normal	WGS	6838bd95-7747-433b-b8bd-957747c33b07	sequencing_experiment	2021-04-05 23:01	wes-28cf3dca451c4ee9a0a05b7f4a4a0a6c	2021-04-05 19:12	['36d7f896-f46c-451e-97f8-96f46ca51e6e', 'a0fc0118-4558-4b65-bc01-184558fb65bd']	duplicated_run_output_analysis
> OCCAMS-GB	DO234346	SA595094	Normal	WGS	6838bd95-7747-433b-b8bd-957747c33b07	sequencing_experiment	2021-04-05 23:01	wes-a28524a6aec24d1d9f16c48890f18e44	2021-04-05 20:04	['259fd268-bc11-40c5-9fd2-68bc11f0c5df', 'e3c3e5d2-46ab-4314-83e5-d246abf314bd']	duplicated_run_output_analysis
> OCCAMS-GB	DO234346	SA595094	Normal	WGS	6838bd95-7747-433b-b8bd-957747c33b07	sequencing_experiment	2021-04-05 23:01	wes-691eaf0a44974eea8bd930d2fbf86ea4	2021-04-05 18:50	['4edc191d-336e-4269-9c19-1d336e426976', 'c096cffa-2b24-4cb5-96cf-fa2b247cb5ac']	duplicated_run_output_analysis
> OCCAMS-GB	DO234255	SA597346	Tumour	WGS	9950139c-bbe4-4c47-9013-9cbbe42c47ed	sequencing_experiment	2021-04-13 9:58	wes-1f49c307eddb4f539113f539f136b025	2021-04-13 7:20	['d121666a-d824-4b97-a166-6ad824cb97de', '4eb815bf-fa69-4eb7-b815-bffa699eb79b']	duplicated_run_output_analysis
> OCCAMS-GB	DO234204	SA597188	Tumour	WGS	6f33dacc-a404-4a63-b3da-cca4048a6327	sequencing_experiment	2021-04-06 0:40	wes-6655ca8d613e4cf1922ff24ad7238e17	2021-04-05 21:03	['517d574f-5710-4f82-bd57-4f57107f8252', '66767029-abb9-44c7-b670-29abb9a4c7a8']	duplicated_run_output_analysis
> OCCAMS-GB	DO234352	SA595137	Tumour	WGS	9110449e-ef5d-4feb-9044-9eef5dafebbc	sequencing_experiment	2021-04-06 17:11	wes-73dd0796861f4c409910d920a134873d	2021-04-06 15:51	['70731493-daa9-447b-b314-93daa9d47b6a', 'c58dcfd4-6b52-49a2-8dcf-d46b5209a252']	duplicated_run_output_analysis
> OCCAMS-GB	DO234352	SA595137	Tumour	WGS	9110449e-ef5d-4feb-9044-9eef5dafebbc	sequencing_experiment	2021-04-06 17:11	wes-f56bf58eccb64c2780290f5c383be74e	2021-04-06 17:06	['cd39cd14-067e-401f-b9cd-14067ee01f55', 'ba2b1b25-242f-44fb-ab1b-25242fd4fb93']	duplicated_run_output_analysis
> OCCAMS-GB	DO234272	SA597337	Tumour	WGS	4ed74435-ce41-4c15-9744-35ce411c153b	sequencing_experiment	2021-04-17 6:44	wes-6f956d6615c0449786df8064c9562090	2021-04-14 10:01	['051f450c-4d30-48df-9f45-0c4d3048df75']	failed_run_output_analysis
> OCCAMS-GB	DO234272	SA597337	Tumour	WGS	4ed74435-ce41-4c15-9744-35ce411c153b	sequencing_experiment	2021-04-17 6:44	wes-f067428c6c184499ac77498299a5dd55			duplicated_running_jobs
> OCCAMS-GB	DO234272	SA597329	Normal	WGS	fbb9ce6c-7331-4661-b9ce-6c7331266182	sequencing_experiment	2021-04-21 11:15	wes-d29c0664c3624313b7f3885297daa14a	2021-04-14 10:02	['75e6d569-27c1-47e8-a6d5-6927c1d7e89e']	failed_run_output_analysis
> OCCAMS-GB	DO234272	SA597329	Normal	WGS	fbb9ce6c-7331-4661-b9ce-6c7331266182	sequencing_experiment	2021-04-21 11:15	wes-788ec8b348524ad4bcd56e0feb5d4533	2021-04-17 6:37	['672bbe58-96a9-4b2d-abbe-5896a94b2de6', 'bdf27793-3dfd-486e-b277-933dfdf86ec2']	duplicated_run_output_analysis

All **output_analysis_to_suppress** in the above table have been suppressed.

**Comment by lindaxiang** [comment] 2021-05-04 18:44
**The Donors to be excluded from May release:**
- OCCAMS-GB WGS:

**Donor**|**Status**|**Note**|**Action**
:-----:|:-----:|:-----:|:-----:
DO234165;DO50319|Missing Normal Aln| 2 donors|Exclude donors
[92_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423282/92_donors.txt) |Missing Sanger| 92 donors|Exclude donors
[51_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423283/51_donors.txt) |Missing both Sanger and Mutect2| 51 donors|Exclude donors
DO234327|Missing both Sanger and Mutect2 for tumour sample SA130945; Missing Sanger for tumour sample SA130946|  |Exclude donors
DO234150 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour samples SA596951 and SA596942| donor is in the release as it has another full datasets|Exclude tumour samples
DO234328 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour sample SA130952| donor is in the release as it has another full datasets|Exclude tumour samples
DO234444 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour sample SA594885| donor is in the release as it has another full datasets|Exclude tumour samples
[25_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423284/25_donors.txt) |Missing both Normal and Tumour Aln;Raw data only exist in Intermediate SONG| 25 donors|Exclude donors
DO234180;DO10859;DO10842|Info only exist in Clinical, No data in SONG| 3 donors|Exclude donors

**Comment by lindaxiang** [comment] 2021-05-04 18:49
Here is some counts for OCCAMS-GB to be released:

**Project**|**Experiment**|**#Donor**|**#Total\_Aln**|**#Normal\_Aln**|**#Tumour\_Aln**|**#Sanger\_Call**|**#Mutect2\_Call**|**PROD dashboard**|**Staging File Repo**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
OCCAMS-GB|WGS|235|470|235|235|235|235|Match|Mismatch for all numbers except #Sanger\_Call

**Closed as completed** 2021-05-12 13:17 UTC
