### ISSUE TITLE
ICGC25K Azure transfer - PACA-AU backlog jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#187] opened 2021-08-12 17:40 UTC
There are 419 PACA-AU jobs are on hold due to this error: 
```
$.sample[0].specimen.specimenType: does not have a value in the enumeration
```

**Comment by junjun-zhang** [comment] 2021-08-12 18:40
basically the SONG analysis being rejected has specimen type: `Primary tumour` which is not the allowed list of:
```
Normal - solid tissue, Normal - blood derived, Normal - bone marrow, Normal - tissue adjacent to primary, Normal - buccal cell, Normal - EBV immortalized, Normal - lymph node, Normal - other, Primary tumour - solid tissue, Primary tumour - blood derived (peripheral blood), Primary tumour - blood derived (bone marrow), Primary tumour - additional new primary, Primary tumour - other, Recurrent tumour - solid tissue, Recurrent tumour - blood derived (peripheral blood), Recurrent tumour - blood derived (bone marrow), Recurrent tumour - other, Metastatic tumour - NOS, Metastatic tumour - lymph node, Metastatic tumour - metastasis local to lymph node, Metastatic tumour - metastasis to distant location, Metastatic tumour - additional metastatic, Xenograft - derived from primary tumour, Xenograft - derived from tumour cell line, Cell line - derived from tumour, Primary tumour - lymph node, Metastatic tumour - other, Cell line - derived from xenograft tumour
```

One way to fix would be updating SONG server side to accept `Primary tumour` for specimen type.

**Comment by akachru-github** [comment] 2021-08-17 17:26
@hknahal to take a look at this as the intention was that the schema should be fully backward compatible with ICGC25k.

**Comment by hknahal** [comment] 2021-08-27 19:36
Failed jobs for PACA-AU: https://github.com/icgc-argo/icgc-25k-azure-transfer-job-tracking/tree/main/jobs/PACA-AU/2021-07-22/failed

All 17 affected samples from PACA-AU are RNA-Seq and have `Primary tumour` as the specimenType in the Collab SONG payloads. However this term (`Primary tumour`) is not part of the controlled vocabulary for [specimen_type](https://docs.icgc.org/dictionary/viewer/#?viewMode=details&dataType=specimen&q=specimen_type) in the ICGC Data Dictionary, and is also not a term in the enum list for `specimenType` in the Collab SONG [sequencingRead schema](https://song.cancercollaboratory.org/schema/sequencingRead
). But the `specimen_type` submitted in ICGC clinical is `Primary tumour - solid tissue` is correct. So it's unclear how the `specimenType` field in the Collab SONG payloads was submitted incorrectly.

Summary:

|donorSubmitterId | donorId | specimenSubmitterId | specimenId | sampleSubmitterId | sampleId | Collab SONG payload (incorrect) specimenType | ICGC Clinical (correct) specimen_type | libraryStrategy|
|-- | -- | -- | -- | -- | -- | -- | -- | --|
|ICGC_0051 | DO32972 | 8015281 | SP70086 | 8015281 | SA409258 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0205 | DO33208 | 8031558 | SP70964 | 8031558 | SA410410 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0007 | DO32833 | 8012195 | SP69571 | 8012195 | SA407918 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0052 | DO33042 | 8015860 | SP70323 | 8015860 | SA409711 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0215 | DO34448 | 8052601 | SP75442 | 8052601 | SA410311 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0143 | DO33408 | 8035570 | SP71584 | 8035570 | SA411029 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0153 | DO33544 | 8044426 | SP71958 | 8044426 | SA411406 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0201 | DO34608 | 8057483 | SP76009 | 8057483 | SA410883 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
|ICGC_0420 | DO49138 | 8067247 | SP107957 | 8067247 | SA518704 | Primary tumour | Primary tumour - solid tissue | RNA-Seq|
ICGC_0214 | DO34432 | 8051980 | SP75250 | 8051980 | SA410118 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0391 | DO49076 | 8067177 | SP107776 | 8067177 | SA518630 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0227 | DO34640 | 8068589 | SP110823 | 8068589 | SA528761 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0146 | DO33480 | 8043985 | SP71766 | 8043985 | SA411209 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0321 | DO34905 | 8061179 | SP77211 | 8061179 | SA412076 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0313 | DO34728 | 8067940 | SP110825 | 8067940 | SA528709 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0312 | DO34793 | 8058334 | SP76875 | 8058334 | SA411745 | Primary tumour | Primary tumour - solid tissue | RNA-Seq
ICGC_0502 | DO49172 | 8069317 | SP110826 | 8069317 | SA528768 | Primary tumour | Primary tumour - solid tissue | RNA-Seq

Possible solution:
- Update `specimenType` in Collab SONG payloads so it is the correct specimen type (`Primary tumour - solid tissue`). Is there an endpoint for this?

**Comment by lindaxiang** [comment] 2021-09-01 14:48
Error messages of failed jobs: 
[PACA-AU_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092111/PACA-AU_job_state.txt)

**Comment by lindaxiang** [comment] 2021-09-01 15:38
Here is the all 156 affected RNA-Seq analysis which contain incorrect `speciment_type`=`Primary tumour`.
[PACA-AU.incorrect_speciment_type.analysis.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092528/PACA-AU.incorrect_speciment_type.analysis.txt)

**Comment by akachru-github** [comment] 2021-09-14 20:13
- Root cause: https://github.com/icgc-argo/workflow-roadmap/issues/197
- This was fixed and the files were re-transferred. 
-

**Closed as completed by akachru-github** 2021-09-14 20:13 UTC
