### ISSUE TITLE
Update analysis to latest sequencing_alignment schema (0.2.0)

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#8] opened 2020-04-21 15:09 UTC
The `sequencing_experiment` analysis type was updated.  specifically, 
- the workflow section contains renamed fields
- genome build was added

The existing payloads on `prod Song` need to be updated to be compliant with the latest schemas: 
https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.2.0

Use the update payload endpoint in Song:
https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html#/Analysis/updateAnalysisUsingPUT

**Comment by junjun-zhang** [comment] 2020-05-19 16:51
Here is the breakdown of completed alignment jobs:
| project | alignment pipeline version | # of jobs | schema version | note |
|--------|-------------|------|-----|----|
| OCCAMS-GB | 1.0.4 | 11 | 0.1.0 | duplicates, should be deleted (to be confirmed)
| OCCAMS-GB | 1.0.5 | 356 | 0.1.1 | |
| OCCAMS-GB | 1.1.0 | 20 | 0.2.0 | |
| OCCAMS-GB | 1.1.1 | 14 | 0.2.0 | |
| PACA-CA  | 1.0.5 | 2 | 0.1.1 | |
| PACA-CA  | 1.1.0 | 52 | 0.2.0 | |
| PACA-CA  | 1.1.1 | 182 | 0.2.0 | |

All SONG payloads need to be migrated to schema version [0.3.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.3.0)

Since we have not run any production job that generates 0.3.0 payload, these two payloads from a testing run should be useful to illustrate how payload 0.3.0 looks like:
* aligned CRAM: https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/e1eb1e10-c5fb-4db9-ab1e-10c5fb2db9a2
* alignment QC metrics: https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/116bc6e4-661d-4f53-abc6-e4661d9f5355

**Comment by lindaxiang** [comment] 2020-06-12 19:08
Both `sequencing_alignment` and `qc_metrics` in `rdpc-prod` have been migrated to latest schema. 
The migration payloads we used are checked into git for tracking purpose: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_migration/2020-06-12

**Closed as completed by lindaxiang** 2020-06-12 19:08 UTC
