### ISSUE TITLE
ICGC25k azure transfer - LIRI-JP failed jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#195] opened 2021-08-30 16:29 UTC
Error messages of failed jobs:
[LIRI-JP_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092104/LIRI-JP_job_state.txt)

**Comment by hknahal** [comment] 2021-09-02 21:18
Summary of failed job:

**1 job failed due to objectID mismatch:**

- Azure SONG assigns the object ID to a different file than Collab SONG:
  Example 1:
   - Collab SONG: https://song.cancercollaboratory.org/studies/LIRI-JP/files/e172a7a5-5712-5f32-ac92-e7bb74a710f6
   - Azure SONG: https://song.azure.icgc.overture.bio/studies/LIRI-JP/files/e172a7a5-5712-5f32-ac92-e7bb74a710f6

The Object ID "e172a7a5-5712-5f32-ac92-e7bb74a710f6" is assigned to a different file in Azure SONG:
```
Object ID: e172a7a5-5712-5f32-ac92-e7bb74a710f6
Collab SONG file name: mini-55aa07d03f6a497af1f0fb36909ae9c3.bam
Azure SONG file name: mini-13f6034648d31da39bd8855d39d1db00.bam.bai
```

**Comment by akachru-github** [comment] 2021-09-14 20:11
- Root cause was discovered: https://github.com/icgc-argo/workflow-roadmap/issues/196
- Data was re-transferred

**Closed as completed by akachru-github** 2021-09-14 20:11 UTC
