### ISSUE TITLE
ICGC azure transfer - PACA-CA failed jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#192] opened 2021-08-30 16:24 UTC
Error messages of failed jobs:
[PACA-CA_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092116/PACA-CA_job_state.txt)

**Comment by lindaxiang** [comment] 2021-09-01 15:50
- 6 jobs failed with payload save `409` error:  `The sample with sampleId 'SA****' already exists.`
- 2 jobs failed with error: `'sampleId' mismatch`

**Comment by lindaxiang** [comment] 2021-09-01 16:05
- 1 job failed with error: `Data file objectId mismatch`
Collab song: https://song.cancercollaboratory.org/studies/PACA-CA/analysis/e4f275a2-4c3d-47df-b8e1-c52f81691ed7
Azure song: https://song.azure.icgc.overture.bio/studies/PACA-CA/analysis/e4f275a2-4c3d-47df-b8e1-c52f81691ed7
same fileName: `9011cf17-0783-4f9d-b355-4f0fc1a2e78b.consensus.20160830.somatic.snv_mnv.vcf.gz.tbi`
mapped to different objectIds in: 
Collab: 61db99bf-eff3-5bbf-b9a7-9a5b7337cf78
Azure: 1db99bf-eff3-5bbf-b9a7-9a5b7337cf78C

**Comment by akachru-github** [comment] 2021-09-14 20:12
- Root cause was discovered: https://github.com/icgc-argo/workflow-roadmap/issues/196
- Data was re-transferred

**Closed as completed by akachru-github** 2021-09-14 20:12 UTC
