### ISSUE TITLE
Technical design for data transfer workflow 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#141] opened 2021-05-11 03:06 UTC
- Technical design for workflow to transfer ICGC25k data to the Azure environment. 
- We want to retain AnalysisID and ObjectID
  - Proposal is to mirror the Song DB in Azure, and transfer the data via Score to meet this requirement
- The prod RDPC environment will be used to run this workflow manually, Model Tee will not be needed. 
- Esophogeal data will not be transferred as it was problematic in ICGC25k. We will reference the corrected ARGO data for this. 

Expected output is a wiki page.

**Comment by junjun-zhang** [comment] 2021-05-19 13:33
Highlevel steps:

- identify ICGC projects that permit data to hosted on comercial clouds, there is an existing list for AWS
- transfer SONG metadata through back donor from Collab SONG instance to the new SONG instance hosted at Azure, and set all analysis to UNPUBLISHED
- for each SONG analysis object to be transfer, download relavant data objects from Collab and store locally
- generate manifest file for upload
- upload data files using score to Azure
- publish SONG analysis at Azure

**Comment by junjun-zhang** [comment] 2021-05-26 18:11
need to modify the current song/score upload workflow to support a new use case where the SONG analysis object already exist, what's left to do is data upload and song publish

**Comment by junjun-zhang** [comment] 2021-05-31 13:47
confirmed via Slack channel that a legacy version of SONG/SCORE (same as DCC portal's) server will be installed in Azure environment, this will make things a lot easier, there is no need to go through back door to pre-populated SONG metadata. The transfer can be done as normal metadata/data download, then metadata submission (using the same SONG analysis ID) and data upload.

**Comment by junjun-zhang** [comment] 2021-06-10 17:39
With some manual testing with the Azure dev SONG/SCORE, here is the design for the data transfer workflow. It includes the following three steps, each is performed by a `wfpm` package:
1. download song metadata and data from Collab
2. submit song payload to Azure SONG server
3. upload upload data to Azure SCORE server and publish the analysis

Since legacy SONG server works differently than the newer SONG, existing SONG/SCORE download/upload `wfpm` packages do not work, need to write new packages.

**Closed as completed** 2021-06-10 17:39 UTC

**Comment by andricDu** [comment] 2021-06-10 18:09
Just to check, where is the output of this ticket?

**Comment by junjun-zhang** [comment] 2021-06-10 18:13
here: https://github.com/icgc-argo/workflow-roadmap/issues/141#issuecomment-858827607

**Comment by junjun-zhang** [comment] 2021-06-10 18:15
followup ticket is #140
