### ISSUE TITLE
ICGC25k azure transfer - CMDI-UK failed jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#193] opened 2021-08-30 16:27 UTC
Here are the error messages of these failed jobs:
[CMDI-UK_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092092/CMDI-UK_job_state.txt)

**Comment by hknahal** [comment] 2021-09-02 20:42
Summary of failed jobs:

**29 jobs failed with sampleId mismatch error:**
- Azure SONG did not create the same IDs as in Collab SONG
 Example:
     - Collab: https://song.cancercollaboratory.org/studies/CMDI-UK/analysis/27676071-5b99-47c6-9005-016c15901c91
     - Azure: https://song.azure.icgc.overture.bio/studies/CMDI-UK/analysis/27676071-5b99-47c6-9005-016c15901c91

The sampleSubmitterId "PD4060e" is assigned a different sampleId in Azure SONG:

      sampleSubmitterId: PD4060e
      Collab sampleId: SA542221
      Azure sampleId: SA542222

- Also, Azure SONG did not create the same number of samples in the payload. In the above example, Collab SONG has 3 samples for this analysis ID, but SONG Azure only included one sample.

**82 jobs failed when trying to save the upload:**
- Azure SONG  does not assign the same sampleId to sampleSubmitterId as Collab SONG.
Example:
   - Collab SONG: https://song.cancercollaboratory.org/studies/CMDI-UK/analysis/48c40fa0-d2ca-11e5-9718-a5315c6878de
   - SONG Azure Upload: https://song.azure.icgc.overture.bio/upload/CMDI-UK/status/UP-b9a9dd37-50a2-4cdb-acf4-27297b1cd37b
     SONG Azure Error message: "The sample with sampleId 'SA542224' already exists"

The  sampleID "SA542224" was assigned to a different sampleSubmitterId in Azure SONG:

      sampleId: SA542224
      Collab  sampleSubmitterId: PD4775c
      Azure  sampleSubmitterId: PD4775f


**2 jobs failed without error message:**

67b2a79c-cee6-11e5-8ba8-ac7e4d100685
91e270d4-7257-4bee-958a-185f32240b4e

**1 job failed with nested exception:**

55f9ad5d-018e-4a8e-93f6-8483bc851037

Error message:
```{"errorId":"unknown.error","httpStatusCode":500,"httpStatusName":"INTERNAL_SERVER_ERROR","requestUrl":"http://song.azure.icgc.overture.bio/upload/CMDI-UK/save/UP-d26edbb1-58e4-4c59-803b-ef3c58067766?ignoreAnalysisIdCollisions=true","datetime":"2021-08-31T20:56:13.07Z[GMT]","timestamp":1630443373070,"message":"Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [specimen_submitter_id_donor_id_uindex]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"```

**Comment by akachru-github** [comment] 2021-09-14 20:11
- Root cause was discovered: https://github.com/icgc-argo/workflow-roadmap/issues/196
- Data was re-transferred

**Closed as completed by akachru-github** 2021-09-14 20:11 UTC
